import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const bmJua = localFont({
  src: '../../public/fonts/BMJUA.woff2',
  weight: '400',
  display: 'swap',
  variable: '--font-bmjua',
});

const nanumRound = localFont({
  src: [
    { path: '../../public/fonts/NanumSquareRoundR.woff2', weight: '400' },
    { path: '../../public/fonts/NanumSquareRoundB.woff2', weight: '700' },
  ],
  display: 'swap',
  variable: '--font-nanum-round',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bmJua.className} ${nanumRound.className} antialiased`}>{children}</body>
    </html>
  );
}
